
output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Gloop Documentation
# this appears on the top navigation bar next to the home button

site_title: Gloop Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Gloop
# this appears in the footer

github_editme_path: tomjohnson1492/documentation-theme-jekyll/blob/gh-pages/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname:
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Gloop Documentation

feedback_email: rob@gloop.io
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      toc: false

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      toc: false

# these are defaults used for the frontmatter for these file types

sidebars:
- home_sidebar
- android_sidebar
- ios_sidebar
- server_sidebar

description: "Gloop Documentation description"
# the description is used in the feed.xml file

# needed for sitemap.xml file only
url: http://gloopio.github.io/Documentation
